# fly.toml app configuration file generated for dark-cloud-1739 on 2023-08-24T10:56:28-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dark-cloud-1739"
primary_region = "sjc"

[build]

[env]
  ARCHIVE_PATH="/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[mounts]
  source="hn_archive"
  destination="/data"
